#[

  A map is a "area" to visit.
  Players are on a map.
  Items lay on the ground.
  Buildings are on the map.
  The 4 sides of a map brings the player to the worldmap screen.
  A map can load a script file to add npc's and other interactions

  They are generated by the mapgen.nim or produced by hand.
]#

type Map = ref object
  size: int
  tiles: string
  items: string


